### ISSUE TITLE
Knapper burde kunne brukes link

### ISSUE THREAD

**Issue by annalytic** [kartverket/kvib#147]
Nå er det kun lagt opp til at knappene kan brukes som html elementet <button/>, men man burde også kunne bruke css-klassene til lenker <a/>

**Comment by nilben** [comment]
Denne er jeg usikker på. Strukturelt så er det forskjell på lenker og knapper. Slik jeg har forstått det så skal knapper brukes til å gjennomføre en action, mens lenker kun flytter deg til en ny side (i samme eller ny tab, og innenfor samme eller ny applikasjon). Med hensyn til tilgjengelighet er det viktig at vi er tydelige på at dette er to forskjellige ting, og da mener jeg også at stylingen bør vise det. Forøvrig mener jeg at vi også bør prioritere å få på plass lenkestyling snart.

Se gjerne også på denne forklaringen fra a11y: https://www.a11y-101.com/design/button-vs-link
