### ISSUE TITLE
Tekst og ikon ikke vertikalt sentrert i small/medium knapper

### ISSUE THREAD

**Issue by annalytic** [kartverket/kvib#150]
![Screenshot 2022-11-16 at 08 46 06](https://user-images.githubusercontent.com/22708819/202118653-86b4da62-7023-484d-94ae-9baa02f9af72.png)

**Comment by nilben** [comment]
Lukker denne, da den gjelder gamle kvib-css biblioteket, som ikke lenger er i bruk.
