### ISSUE TITLE
Knapp vil ikke tilpasse seg teksen i enkelte tilfeller (v5.0.0)

### ISSUE THREAD

**Issue by Gauteab** [kartverket/kvib#194]
Jeg opplevde at knappene ble veldig store fordi det ikke var plass til teksten "Legg til".
![image](https://user-images.githubusercontent.com/25511262/227244691-a1a320f6-50c3-4ac1-affd-421007493fe0.png)
Jeg fikk jobba meg rundt det ved å gjøre parent til `flex` i stedet for `grid`, og gi knappen `min-width: fit-content`.
Er det en mer robust måte å sette størrelsene til knappen?

Dette er kanskje litt tricky å reprodusere, men gjør et forsøk på å lage issue allikevel 😇

**Comment by nilben** [comment]
Lukker denne, da den ser ut til å gjelde KVIB-css pakken, som ikke lenger er i bruk.
