### ISSUE TITLE
Sidemeny: Vanskelig å navigere og få oversikt over komponenter

### ISSUE THREAD

**Issue by magnusmodol** [kartverket/kvib#854]
### Tilbakemelding

**Vanskelig å navigere seg i menyen på venstre side.**
Ikke lett å forstå informasjonsarkitekturen og hvordan ting er satt opp i forhold til hverandre ved første øyekast.

**Mulige forbedringer:**
- Ha bakgrunnsfarge på åpnede elementer. For eksempel at dersom man åpner "Layout", vil alle elementene tilhørende denne siden også få en lik bakgrunnsfarge som viser en slags "active-state".
- Gruppere elementer som hører sammen, og ha mer mellomrom mellom de elementene som ikke hører sammen.
- Breadcrumbs inne på alle sidene, slik at man lett kan komme seg tilbake til forrige side - i tillegg til å få en oversikt over hvordan alt henger sammen.

![Screenshot 2024-09-24 at 10 08 33](https://github.com/user-attachments/assets/9c71359f-f186-403c-a8bf-bf412a1cc37c)

**Comment by chrhein** [comment]
Supert innspill! Skal få sett på dette en dag, enig i at det kan gjøres et lite løft som øker lesbarheten her ☺️

**Comment by joonerik** [comment]
Kanonfiks 👌 🚀
