### ISSUE TITLE
[Nytt komponent]: DateRangePicker med mulighet til å velge et tidsintervall

### ISSUE THREAD

**Issue by magnusmodol** [kartverket/kvib#875]
### Navn på komponent

DateRangePicker

### Eksempel på komponentet

I dag har Kartverket Datepicker, men dersom man ønsker å velge et gitt tidsintervall mellom to datoer må man i dag lage denne logikken selv ved hjelp av to Datepicker-komponenter. Jeg ønsker å pitche idéen om å lage et DateRangePicker-komponent som forenkler denne prosessen for både brukere og de som koder.

Jeg ser på DateRangePicker som et komponent som er "nice to have". Man finner ofte dette komponentet på flere nettsider og apper, men er strengt tatt ikke nødvendig for å velge et tidsintervall mellom to datoer.

Eksempel på hvordan DateRangePicker kan fungere og se ut:
![image](https://github.com/user-attachments/assets/7a91c1d3-961f-4512-bc35-9974c5b08b37)

Eksempel på lignende kode:
https://mui.com/x/react-date-pickers/date-range-picker/

**Comment by chrhein** [comment]
Knallbra innspill, lager en sak på det!
